version: "3"

services:
  mosquitto:
    image: eclipse-mosquitto:2.0.18
    container_name: mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    restart: always
  mongo:
    image: mongo:5.0.22
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data_configdb:/data/configdb
      - mongo_data_db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    restart: always
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: ${ME_CONFIG_MONGODB_URL}
    depends_on:
      - mongo
    restart: always
  ml-processor:
    build: ./ml-processor
    container_name: ml-processor
    ports:
      - "8000:8000"
    restart: always
  kernel:
    build: ./kernel
    container_name: kernel
    ports:
      - "8080:8080"
    environment:
      ML_PROCESSOR_URL: http://ml-processor:8000/data
      MONGODB_URL: ${ME_CONFIG_MONGODB_URL}
      MQTT_HOST: mosquitto
    depends_on:
      - mosquitto
      - mongo
      - ml-processor
    restart: always
  processor:
    build: ./processor
    container_name: processor
    ports:
      - "8082:8082"
    environment:
      MONGODB_URL: ${ME_CONFIG_MONGODB_URL}
      DASHBOARD_URL: http://dashboard:3000
    depends_on:
      - mongo
    restart: always
  dashboard:
    build: ./dashboard
    container_name: dashboard
    ports:
      - "3000:3000"
    environment:
      PROCESSOR_URL: http://processor:8082
    depends_on:
      - processor
    restart: always
  # proxy:
  #   image: nginx:latest
  #   volumes:
  #     - ./proxy/nginx.conf:/etc/nginx/nginx.conf
  #   ports:
  #     - "8888:80"
  #   environment:
  #     - NGINX_HOST=foobar.com
  #     - NGINX_PORT=80
  #   restart: always

volumes:
  mongo_data_configdb:
  mongo_data_db:
